allow_missing_labels: false
charge_weight: 0.0
data_mean: 0.0
data_std: 1.0
decay_alpha: 0.01
decay_steps: 1000
element_refs: !!python/object/apply:numpy._core.multiarray._reconstruct
  args:
  - !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 2
  - !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - false
  - !!binary |
    MTMzMzPzE8AzMzMzM/MTwA==
energy_weight: 1.0
force_weight: 1.0
include_line_graph: false
loss: huber_loss
loss_params: null
lr: 0.001
magmom_target: absolute
magmom_weight: 0.0
optimizer: null
scheduler: null
stress_weight: 0.1
sync_dist: false
